package com.gardle.web.rest.errors;

public enum GardleErrorKey {
    //User and Account
    EMAIL_ALREADY_EXISTS,
    EMAIL_NOT_FOUND,
    PASSWORD_INVALID_LENGTH,
    LOGIN_ALREADY_EXISTS,
    MISSING_AUTHORITY,
    USER_ID_ALREADY_EXISTS,
    USER_NOT_LOGGED_IN,
    USER_NOT_AUTHORIZED_FOR_REQUESTED_GARDENFIELD,
    NO_USER_FOUND_FOR_ACTIVATION_KEY,
    USER_NOT_FOUND,
    CURRENT_LOGIN_NOT_FOUND,
    USER_FOR_RESET_KEY_NOT_FOUND,
    ACCESS_DENIED,
    PASSWORD_INVALID,

    //Gardenfield
    GARDENFIELD_FILTER_CRITERIA_VALIDATION,
    GARDENFIELD_NOT_FOUND,
    GARDENFIELD_WITHOUT_OWNER,
    GARDENFIELD_ID_ALREADY_EXISTS,
    CANNOT_CREATE_GARDENFIELD_FOR_ANOTHER_USER,

    //Gardenfield images
    IMAGE_NOT_FOUND,
    COVER_NOT_FOUND,
    IMAGE_STORAGE,
    NOT_AN_IMAGE,
    COULD_NOT_DELETE_IMAGE,
    IMAGE_INVALID_RESOURCE_PATH,

    //Leasing
    LEASINGS_OVERLAP,
    LEASING_ID_ALREADY_EXISTS,
    LEASING_INVALID_ID,
    LEASING_NOT_FOUND,
    LEASING_STATUS_TRANSITION_NOT_ALLOWED,
    LEASING_UPDATE_NOT_ALLOWED_IN_PERIOD,
    LEASING_CREATE_NOT_ALLOWED_IN_PERIOD,
    LEASING_TOO_SHORT,
    LEASING_USER_DOES_NOT_EXIST,

    //Message
    USER_NOT_AUTHORIZED_FOR_REQUESTED_MESSAGE_THREAD,
    USER_NOT_AUTHORIZED_FOR_REQUESTED_MESSAGES,

    //Payment
    PAYMENT_ID_ALREADY_EXISTS,
    PAYMENT_INVALID_ID,
    PAYMENT_OF_LEASING_NOT_SET,
    MISSING_BANK_ACCOUNT_IBAN,
    MISSING_BANK_ACCOUNT_EMAIL,
    PAYMENT_PROVIDER_ERROR,

    //Server
    INTERNAL_SERVER_ERROR,
    VALIDATION_ERROR,

    //general
    MISSING_PERMISSION,
    // stripe
    STRIPE_VERIFICATION_KEY_VALIDATION_ERROR,
    MISSING_STRIPE_VERIFICATION
}
